mappings:
  HybridSessionDataObject: SilverStripe\HybridSessions\Model\HybridSessionDataObject
  HybridSessionStore_Crypto: SilverStripe\HybridSessions\Crypto\HybridSessionCrypto
  HybridSessionStore_Base: SilverStripe\HybridSessions\Store\BaseStore
  HybridSessionStore_Cookie: SilverStripe\HybridSessions\Store\CookieStore
  HybridSessionStore_Database: SilverStripe\HybridSessions\Store\DatabaseStore
  HybridSessionStore: SilverStripe\HybridSessions\Store\SessionStore
